### PR TITLE
Test files

### PR DESCRIPTION
**Pull request by almahmoud**

### CODE REVIEW

**Comment by almahmoud** [comment]
Release "galaxy-preview-7" does not exist. Installing it now. NAME: galaxy-preview-7 LAST DEPLOYED: Sun Jul 26 04:00:21 2020 NAMESPACE: default STATUS: deployed REVISION: 1 NOTES: 1. Get the application URL by running these commands: https://localhost/issue-7/galaxy/ https://beta5jsdev.usegvl.org/issue-7/galaxy/

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-7" does not exist. Installing it now. NAME: galaxy-preview-7 LAST DEPLOYED: Sun Jul 26 04:12:31 2020 NAMESPACE: default STATUS: deployed REVISION: 1 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-7/galaxy

**Pull request closed without merging**
